#! /bin/sh

./uninstall

stow --adopt . #maybe uninstall could be just stow -D (delete)
cd $HOME/.dotfiles/.config/nvim && git checkout main

MONITORS=$(xrandr | grep -sw 'connected' | wc -l)

case $MONITORS in
    1)
        echo "You have selected a Single Monitor setup."
        ln -s $HOME/.dotfiles/.config/i3/single_monitor_config $HOME/.config/i3/config
        ;;
    2)
        echo "Dual Monitor setup"
        ln -s $HOME/.dotfiles/.config/i3/dual_monitor_config $HOME/.config/i3/config
        ;;
    *)
        echo "More than 2? I was not prepared to that. Defaulting to Dual Monitor setup"
        ln -s $HOME/.dotfiles/.config/i3/dual_monitor_config $HOME/.config/i3/config
        ;;
esac
