#! /bin/sh

./uninstall

stow --adopt . #maybe uninstall could be just stow -D (delete)
xrdb ~/.Xresources
cd ~/.dotfiles/.config/nvim && git checkout main

mkdir -p $HOME/.config/i3

case $1 in
    "single")
        echo "You have selected a Single Monitor setup."
        ln -s $HOME/.dotfiles/.config/i3/single_monitor_config $HOME/.config/i3/config
        ;;
    "dual")
        echo "You have selected a Dual Monitor setup."
        ln -s $HOME/.dotfiles/.config/i3/dual_monitor_config $HOME/.config/i3/config
        ;;
    *)
        echo "Defaulting to Dual Monitor setup"
        ln -s $HOME/.dotfiles/.config/i3/dual_monitor_config $HOME/.config/i3/config
        ;;
esac

        ln -s $HOME/.dotfiles/.config/i3/wallpaper.png $HOME/.config/i3/
