#! /bin/sh

choice=-1

echo Choose dotfiles to be removed:
echo [1] Desktop
echo [2] Laptop

while true; do
    read choice
    if [ "$choice" -eq 1 ]; then
        DIR="$(pwd)/desktop"
        break
    elif [ "$choice" -eq 2 ]; then
        DIR="$(pwd)/laptop"
        break
    else
        echo "Invalid input"
    fi
done

if [ "$choice" -eq 1 ]; then
    cd $DIR && stow -D --target=$HOME alacritty
elif [ "$choice" -eq 2 ]; then
    cd $DIR && stow -D --target=$HOME urxvt
fi

cd $DIR && stow -D --target=$HOME git
cd $DIR && stow -D --target=$HOME i3wm
cd $DIR && stow -D --target=$HOME vim
cd $DIR && stow -D --target=$HOME zsh
