#! /bin/sh

RED='\033[0;31m'
GREEN='\033[0;32m'
MAGENTA='\033[0;35m'
ENDCOLOR='\033[0m'

echo "$GREEN""Updating nvim repo$ENDCOLOR"
cd $HOME/.dotfiles/desktop/vim/nvim && git pull
git add . && git commit -m "autoupdate" && git push
echo "$GREEN""--------------------------------$ENDCOLOR"
echo "$GREEN""Updating .dotfiles repo$ENDCOLOR"
cd $HOME/.dotfiles && git pull
git add . && git commit -m "autoupdate" && git push
echo "$GREEN""--------------------------------$ENDCOLOR"
