#!/usr/bin/env bash
echo "notas-faculdade"
cd $HOME/repos/notas-faculdade/ && git pull && git add . && git commit -m "don't really matters" && git push
echo "---------------------------------"
echo ".dotfiles"
cd $HOME/.dotfiles && git pull && git add . && git commit -m "don't really matters" && git push
echo "---------------------------------"
echo "vault"
cd $HOME/vault && git pull && git add . && git commit -m "don't really matters" && git push
